poses:
  ready_pick:
    frame_id: "link0"
    position: [0.40, 0.00, 0.50]
    orientation: [0.0, 1.0, 0.0, 0.0]

  pre_pick:
    frame_id: "link0"
    position: [0.65, 0.00, 0.44]
    orientation: [0.0, 1.0, 0.0, 0.0]

  pick:
    frame_id: "link0"
    position: [0.65, 0.00, 0.25]
    orientation: [0.0, 1.0, 0.0, 0.0]

  ready_pass: 
    frame_id: "link0"
    position: [0.20, 0.40, 0.50]
    orientation: [0.0, 1.0, 0.0, 0.0]

  pre_pass:
    frame_id: "link0"
    position: [0.20, 0.40, 0.50]
    orientation: [0.0, 1.0, 0.0, 0.0]

  pass_orient:
    frame_id: "link0"
    position: [0.20, 0.40, 0.70]
    orientation: [0.0, 1.0, 0.0, 0.0]

  pass:
    frame_id: "link0"
    position: [0.20, 0.50, 0.55]
    orientation: [0.0, 1.0, 0.0, 0.0]

task:
  step_wait_sec: 0.5
  auto_start: true
