controller_manager:
  ros__parameters:
    update_rate: 100

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController


gripper_controller:
  ros__parameters:
    joints:
      - left_finger_joint
      - right_finger_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0
    action_monitor_rate: 20.0

    allow_partial_joints_goal: false

    constraints:
      stopped_velocity_tolerance: 0.001
      goal_time: 0.5

      left_finger_joint:
        trajectory: 0.002
        goal: 0.002

      right_finger_joint:
        trajectory: 0.002
        goal: 0.002